# Generated by Django 5.1.1 on 2024-09-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("string_field", models.CharField(max_length=255)),
                ("integer_field", models.IntegerField()),
                ("boolean_field", models.BooleanField()),
                ("date_field", models.DateField()),
            ],
            options={
                "verbose_name": "My Model",
                "verbose_name_plural": "My Models",
            },
        ),
    ]
